name: Update readme ⭐️ progress

on:
    schedule:
        - cron: "46 */6 * * *" # Every 6 hours
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        if: ${{ vars.AOC_ENABLED == 'true' }}
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Update ⭐️ Star Table
              uses: k2bd/advent-readme-stars@v1
              with:
                  userId: ${{ secrets.AOC_USER_ID }}
                  sessionCookie: ${{ secrets.AOC_SESSION }}
                  year: ${{ secrets.AOC_YEAR }}

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "⭐️ update readme progress"
