name: Update readme ⭐️ progress

on:
    schedule:
        - cron: "46 */6 * * *" # Every 6 hours
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        permissions:
             contents: write
        steps:
            - uses: actions/checkout@v3
              if: ${{ vars.AOC_ENABLED == 'true' }}
            - uses: k2bd/advent-readme-stars@v1
              if:  ${{ vars.AOC_ENABLED == 'true' }}
              with:
                  userId: ${{ secrets.AOC_USER_ID }}
                  sessionCookie: ${{ secrets.AOC_SESSION }}
                  year: ${{ secrets.AOC_YEAR }}
            - uses: stefanzweifel/git-auto-commit-action@v4
              if:  ${{ vars.AOC_ENABLED == 'true' }}
              with:
                  commit_message: "⭐️ update readme progess"
